/*
 * Copyright (c) 2013.
 * Maxim Matvienko - maxiru (r) LLC.
 * All Right Reserved, http://www.maxiru.com/
 */

package util

/**
 * User: max
 * Date: 2/11/13
 * Time: 2:02 PM
 */
object Ref {

  val mainCategories = List(
    "Baby:Diapering:Diaper Bags",
    "Baby:Strollers",
    "Business & Industrial:Office:Office Supplies:Calendars & Planners:Planners & Organizers",
    "Business & Industrial:Office:Office Supplies:Desk Accessories:Desk & Drawer Organizers",
    "Business & Industrial:Office:Office Supplies:Desk Accessories:Other",
    "Business & Industrial:Office:Office Supplies:Other",
    "Business & Industrial:Office:Other",
    "Cameras & Photo:Camera & Photo Accessories:Other",
    "Cell Phones & Accessories:Cell Phone Accessories:Cases, Covers & Skins",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Baby Accessories:Hats",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Baby Accessories:Other",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Baby Shoes",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Boys' Clothing (Newborn-5T):Bottoms",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Boys' Clothing (Newborn-5T):Outerwear",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Boys' Clothing (Newborn-5T):Sweaters",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Boys' Clothing (Newborn-5T):Tops & T-Shirts",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Girls' Clothing (Newborn-5T):Bottoms",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Girls' Clothing (Newborn-5T):Dresses",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Girls' Clothing (Newborn-5T):Other",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Girls' Clothing (Newborn-5T):Outerwear",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Girls' Clothing (Newborn-5T):Skirts",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Girls' Clothing (Newborn-5T):Sweaters",
    "Clothing, Shoes & Accessories:Baby & Toddler Clothing:Girls' Clothing (Newborn-5T):Tops & T-Shirts",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Accessories:Belts & Belt Buckles",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Accessories:Hats",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Accessories:Other",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Jeans",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Outerwear",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Pants",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Shorts",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Sleepwear",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Socks",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Sweaters",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Sweatshirts & Hoodies",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Tops, Shirts & T-Shirts",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Clothing (Sizes 4 & Up):Underwear",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Boys' Shoes",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Accessories:Backpacks",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Accessories:Belts & Belt Buckles",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Accessories:Gloves & Mittens",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Accessories:Hats",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Accessories:Purses & Wallets",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Dresses",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Jeans",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Leggings",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Outerwear",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Pants",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Shorts",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Skirts",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Skorts",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Sleepwear",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Socks & Tights",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Sweaters",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Sweatshirts & Hoodies",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Swimwear",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Tops, Shirts & T-Shirts",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Clothing (Sizes 4 & Up):Underwear",
    "Clothing, Shoes & Accessories:Kids' Clothing, Shoes & Accs:Girls' Shoes",
    "Clothing, Shoes & Accessories:Men's Accessories:Backpacks, Bags & Briefcases",
    "Clothing, Shoes & Accessories:Men's Accessories:Belts",
    "Clothing, Shoes & Accessories:Men's Accessories:Hats",
    "Clothing, Shoes & Accessories:Men's Accessories:Other",
    "Clothing, Shoes & Accessories:Men's Accessories:Scarves",
    "Clothing, Shoes & Accessories:Men's Accessories:Sunglasses",
    "Clothing, Shoes & Accessories:Men's Accessories:Ties",
    "Clothing, Shoes & Accessories:Men's Accessories:Umbrellas",
    "Clothing, Shoes & Accessories:Men's Accessories:Wallets",
    "Clothing, Shoes & Accessories:Men's Clothing:Blazers & Sport Coats",
    "Clothing, Shoes & Accessories:Men's Clothing:Casual Shirts",
    "Clothing, Shoes & Accessories:Men's Clothing:Coats & Jackets",
    "Clothing, Shoes & Accessories:Men's Clothing:Jeans",
    "Clothing, Shoes & Accessories:Men's Clothing:Pants",
    "Clothing, Shoes & Accessories:Men's Clothing:Shorts",
    "Clothing, Shoes & Accessories:Men's Clothing:Socks",
    "Clothing, Shoes & Accessories:Men's Clothing:Sweaters",
    "Clothing, Shoes & Accessories:Men's Clothing:Sweats & Hoodies",
    "Clothing, Shoes & Accessories:Men's Clothing:T-Shirts",
    "Clothing, Shoes & Accessories:Men's Clothing:Underwear",
    "Clothing, Shoes & Accessories:Men's Clothing:Vests",
    "Clothing, Shoes & Accessories:Men's Shoes:Athletic",
    "Clothing, Shoes & Accessories:Men's Shoes:Boots",
    "Clothing, Shoes & Accessories:Men's Shoes:Casual",
    "Clothing, Shoes & Accessories:Men's Shoes:Dress/Formal",
    "Clothing, Shoes & Accessories:Men's Shoes:Occupational",
    "Clothing, Shoes & Accessories:Men's Shoes:Sandals & Flip Flops",
    "Clothing, Shoes & Accessories:Men's Shoes:Slippers",
    "Clothing, Shoes & Accessories:Unisex Clothing, Shoes & Accs:Other",
    "Clothing, Shoes & Accessories:Unisex Clothing, Shoes & Accs:Unisex Accessories:Bags & Backpacks",
    "Clothing, Shoes & Accessories:Unisex Clothing, Shoes & Accs:Unisex Accessories:Belts",
    "Clothing, Shoes & Accessories:Unisex Clothing, Shoes & Accs:Unisex Accessories:Gloves & Mittens",
    "Clothing, Shoes & Accessories:Unisex Clothing, Shoes & Accs:Unisex Accessories:Hats",
    "Clothing, Shoes & Accessories:Unisex Clothing, Shoes & Accs:Unisex Accessories:Other",
    "Clothing, Shoes & Accessories:Unisex Clothing, Shoes & Accs:Unisex Accessories:Sunglasses",
    "Clothing, Shoes & Accessories:Unisex Clothing, Shoes & Accs:Unisex Accessories:Umbrellas",
    "Clothing, Shoes & Accessories:Women's Accessories:Belts",
    "Clothing, Shoes & Accessories:Women's Accessories:Gloves & Mittens",
    "Clothing, Shoes & Accessories:Women's Accessories:Hair Accessories",
    "Clothing, Shoes & Accessories:Women's Accessories:Hats",
    "Clothing, Shoes & Accessories:Women's Accessories:Other",
    "Clothing, Shoes & Accessories:Women's Accessories:Scarves & Wraps",
    "Clothing, Shoes & Accessories:Women's Accessories:Sunglasses",
    "Clothing, Shoes & Accessories:Women's Accessories:Umbrellas",
    "Clothing, Shoes & Accessories:Women's Accessories:Wallets",
    "Clothing, Shoes & Accessories:Women's Clothing:Athletic Apparel",
    "Clothing, Shoes & Accessories:Women's Clothing:Coats & Jackets",
    "Clothing, Shoes & Accessories:Women's Clothing:Dresses",
    "Clothing, Shoes & Accessories:Women's Clothing:Hosiery & Socks:Pantyhose & Tights",
    "Clothing, Shoes & Accessories:Women's Clothing:Hosiery & Socks:Socks",
    "Clothing, Shoes & Accessories:Women's Clothing:Intimates & Sleep:Camisoles & Camisole Sets",
    "Clothing, Shoes & Accessories:Women's Clothing:Intimates & Sleep:Panties",
    "Clothing, Shoes & Accessories:Women's Clothing:Intimates & Sleep:Sleepwear & Robes",
    "Clothing, Shoes & Accessories:Women's Clothing:Jeans",
    "Clothing, Shoes & Accessories:Women's Clothing:Jumpsuits & Rompers",
    "Clothing, Shoes & Accessories:Women's Clothing:Leggings",
    "Clothing, Shoes & Accessories:Women's Clothing:Pants",
    "Clothing, Shoes & Accessories:Women's Clothing:Shorts",
    "Clothing, Shoes & Accessories:Women's Clothing:Skirts",
    "Clothing, Shoes & Accessories:Women's Clothing:Sweaters",
    "Clothing, Shoes & Accessories:Women's Clothing:Sweats & Hoodies",
    "Clothing, Shoes & Accessories:Women's Clothing:Swimwear",
    "Clothing, Shoes & Accessories:Women's Clothing:T-Shirts",
    "Clothing, Shoes & Accessories:Women's Clothing:Tops & Blouses",
    "Clothing, Shoes & Accessories:Women's Clothing:Vests",
    "Clothing, Shoes & Accessories:Women's Handbags & Bags:Backpacks & Bookbags",
    "Clothing, Shoes & Accessories:Women's Handbags & Bags:Briefcases & Laptop Bags",
    "Clothing, Shoes & Accessories:Women's Handbags & Bags:Handbags & Purses",
    "Clothing, Shoes & Accessories:Women's Shoes:Athletic",
    "Clothing, Shoes & Accessories:Women's Shoes:Boots",
    "Clothing, Shoes & Accessories:Women's Shoes:Flats & Oxfords",
    "Clothing, Shoes & Accessories:Women's Shoes:Heels",
    "Clothing, Shoes & Accessories:Women's Shoes:Occupational",
    "Clothing, Shoes & Accessories:Women's Shoes:Sandals & Flip Flops",
    "Clothing, Shoes & Accessories:Women's Shoes:Slippers",
    "Collectibles:Decorative Collectibles:Decorative Collectible Brands:Swarovski:Other",
    "Computers/Tablets & Networking:Laptop & Desktop Accessories:Laptop Cases & Bags",
    "Computers/Tablets & Networking:iPad/Tablet/eBook Accessories:Cases, Covers, Keyboard Folios",
    "Consumer Electronics:Portable Audio & Headphones:Headphones",
    "Consumer Electronics:Portable Audio & Headphones:iPod, Audio Player Accessories:Audio Docks & Mini Speakers",
    "Crafts:Kids' Crafts:Craft Kits",
    "Health & Beauty:Fragrances:Children",
    "Health & Beauty:Fragrances:Men",
    "Health & Beauty:Fragrances:Women",
    "Health & Beauty:Makeup:Eyes:Eyeliner",
    "Health & Beauty:Makeup:Face:Blush",
    "Health & Beauty:Makeup:Lips:Lip Gloss",
    "Health & Beauty:Makeup:Makeup Bags & Cases:Cosmetic Bags",
    "Health & Beauty:Nail Care & Polish:Files & Implements",
    "Health & Beauty:Nail Care & Polish:Nail Art",
    "Health & Beauty:Nail Care & Polish:Nail Polish",
    "Home & Garden:Home Decor:Candles",
    "Home & Garden:Yard, Garden & Outdoor Living:Outdoor Cooking & Eating:Ice Chests & Coolers",
    "Jewelry & Watches:Children's Jewelry:Bracelets",
    "Jewelry & Watches:Children's Jewelry:Other",
    "Jewelry & Watches:Engagement & Wedding:Engagement Rings:Diamond",
    "Jewelry & Watches:Engagement & Wedding:Engagement Rings:Other",
    "Jewelry & Watches:Engagement & Wedding:Engagement/Wedding Ring Sets:Other",
    "Jewelry & Watches:Engagement & Wedding:Other",
    "Jewelry & Watches:Engagement & Wedding:Wedding & Anniversary Bands:Other",
    "Jewelry & Watches:Fashion Jewelry:Bracelets",
    "Jewelry & Watches:Fashion Jewelry:Charms & Charm Bracelets",
    "Jewelry & Watches:Fashion Jewelry:Earrings",
    "Jewelry & Watches:Fashion Jewelry:Necklaces & Pendants",
    "Jewelry & Watches:Fashion Jewelry:Other",
    "Jewelry & Watches:Fashion Jewelry:Rings",
    "Jewelry & Watches:Fine Jewelry:Fine Bracelets:Other",
    "Jewelry & Watches:Fine Jewelry:Fine Earrings:Other",
    "Jewelry & Watches:Fine Jewelry:Fine Necklaces & Pendants:Other",
    "Jewelry & Watches:Fine Jewelry:Fine Rings:Other",
    "Jewelry & Watches:Fine Jewelry:Other",
    "Jewelry & Watches:Men's Jewelry:Other",
    "Jewelry & Watches:Other",
    "Jewelry & Watches:Watches:Other",
    "Jewelry & Watches:Watches:Wristwatches",
    "Music:Storage & Media Accessories",
    "Pet Supplies:Dog Supplies:Carriers & Totes",
    "Sporting Goods:Exercise & Fitness:Gym, Workout & Yoga:Gym Bags",
    "Sporting Goods:Golf:Bags",
    "Sporting Goods:Outdoor Sports:Camping & Hiking:Backpacks:Hydration Packs",
    "Sporting Goods:Outdoor Sports:Camping & Hiking:Backpacks:Internal Frame Packs",
    "Sporting Goods:Outdoor Sports:Camping & Hiking:Backpacks:Other",
    "Sporting Goods:Outdoor Sports:Hunting:Bags & Packs",
    "Sporting Goods:Outdoor Sports:Skateboarding & Longboarding:Other",
    "Sporting Goods:Water Sports:Other",
    "Sporting Goods:Winter Sports:Bags & Backpacks",
    "Travel:Luggage Accessories:Luggage Tags",
    "Travel:Travel Accessories:Locks",
    "Travel:Travel Accessories:Money Belts & Wallets",
    "Travel:Travel Accessories:Other"
  )

  val mainBrands = List(
    "Adidas",
    "Aeropostale",
    "Anne Klein",
    "Armani",
    "AX Armani Exchange",
    "Bali",
    "Banana Republic",
    "Boss",
    "Bulova",
    "Burberry",
    "Bvlgari",
    "Calvin Klein",
    "Carlo Fellini",
    "Cartier",
    "Casio",
    "Champion",
    "Chanel",
    "Christian Dior",
    "Citizen",
    "Coach",
    "Converse",
    "Diesel",
    "DKNY",
    "D&G",
    "Dolce & Gabbana",
    "Dooney & Bourke",
    "Dr. Koffer",
    "eBags",
    "Echo",
    "Fila",
    "Fossil",
    "Giorgio Armani",
    "Gucci",
    "Guess",
    "Gymboree",
    "Hanes",
    "Harley-Davidson",
    "Hugo Boss",
    "Invicta",
    "Jessica Simpson",
    "JJ Cole",
    "Jos. A. Bank Clothiers",
    "Juicy Couture",
    "Keds",
    "Kenneth Cole",
    "Kenneth Cole Reaction",
    "Lacoste",
    "Lancaster",
    "Levis",
    "Marc Jacobs",
    "Michael Kors",
    "Movado",
    "Nautica",
    "New Balance",
    "Nike",
    "Paris Hilton",
    "Playtex",
    "Polaroid",
    "Polo Ralph Lauren",
    "Prada",
    "Puma",
    "Reebok",
    "Reeds",
    "Roxy",
    "Salvatore Ferragamo",
    "Seiko",
    "Skagen",
    "Skechers",
    "Swatch",
    "Tag Heuer",
    "Tiffany",
    "Timberland",
    "Timex",
    "Tommy Hilfiger",
    "Under Armour",
    "Valentino",
    "Versace",
    "Wonderbra",
    "Yves Saint Laurent"
  )

}
